<a href="https://colab.research.google.com/github/Mayank-Bansal24/LAPLSTM-Models/blob/main/Alltimebest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [101]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import losses as lo_ss
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense, Dropout
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.preprocessing import StandardScaler
import seaborn as sns
from sklearn import model_selection

In [102]:
from sklearn.datasets import make_classification
from sklearn.utils import class_weight
from sklearn.metrics import classification_report , roc_auc_score

In [103]:
import os
github_raw_link="https://raw.githubusercontent.com/Aryansh085/LAP/main/858417d1-7d54-4115-a01b-fdda5e03ada3_testing_combined_rows4035_disc_1_0p9_MULTIPLY_preproces_155cols.csv"
df1=pd.read_csv((github_raw_link),header = None)
dftemp=np.array(df1)
dftemp.shape
dftemp2=dftemp[:,5:]
dftemp2=np.array(dftemp2)
print(dftemp2.shape)

(4035, 150)


In [104]:
dftemp2

array([[ 5928.83335518,   796.35823886, -2237.60161204, ...,
          -15.699306  ,  -114.85299429,  -125.04863114],
       [ -861.30872747,  2307.82893916,  1422.32841779, ...,
           13.9362878 ,   261.75236954,    15.2645003 ],
       [-1851.18887014, -1823.48970586, -1483.76235541, ...,
          -63.85885517,   -79.85176543,   -36.49683727],
       ...,
       [ 7523.64392668, -1346.51804904,  -437.24597374, ...,
         -357.30718089,  -178.38042189,    75.12132205],
       [-1639.43181652,  3837.66082759,  -218.35057395, ...,
         -194.79629389,  -248.0217652 ,  -117.95138105],
       [-1687.91842227, -1416.74591555,  1508.833009  , ...,
         -174.86338979,   158.6163271 ,    23.58951279]])

--> muliply the reward of that instance into the loss of that instance to give weight

In [105]:
# df.dropna()

In [106]:
dftemp2.shape

(4035, 150)

In [107]:
from sklearn.preprocessing import StandardScaler


slr=StandardScaler()
slr.fit(dftemp2)
dftemp2 = slr.transform(dftemp2)

In [108]:

dftemp2=pd.DataFrame(dftemp2)
dftemp2.head()


0         1         2         3         4         5         6    \
0  1.750036  0.350342 -1.341973 -2.795068  0.432952  0.474938 -1.574554   
1 -0.254578  1.008169  0.819884 -1.666252 -0.495354 -0.246320 -0.306173   
2 -0.546815 -0.789877 -0.896693  0.609252 -1.785813  0.671458 -1.346309   
3  1.129433  1.576726 -1.089738 -0.159556 -0.237411 -0.771867  1.524618   
4 -0.692797 -0.435498 -1.673149  0.045856  0.292185 -1.561811  0.780544   

        7         8         9    ...       140       141       142       143  \
0 -0.439485 -1.486932 -1.585869  ... -1.015021 -0.795066 -1.952407 -0.866407   
1 -0.182138  0.162858 -0.850303  ...  1.485140 -0.294316  1.076433 -0.578114   
2  0.051911  1.257504  0.635510  ...  1.064428  0.506085 -0.692270  0.803917   
3 -0.068071 -0.171521  0.341681  ... -0.958503 -0.795708 -0.132790  0.018378   
4 -0.000231 -1.402506  0.866888  ...  0.353773 -1.160216 -0.357106  0.220035   

        144       145       146       147       148       149  
0 -3.145759  3.099274 -0.818265 -0.095863 -0.652975 -0.693894  
1  0.625668  0.116021  1.182070  0.071192  1.467883  0.099011  
2  0.736296 -0.473514  0.512632 -0.367337 -0.455865 -0.193491  
3 -0.432966 -0.066116 -0.006371 -0.472373  0.181778  0.074862  
4  0.144812 -0.401812  0.585473 -0.644445  0.811905 -0.621054  

[5 rows x 150 columns]

In [109]:
t=3

In [110]:
y=np.array(dftemp[:,0])
print(y)
y_new=y[t:]
y_new.shape


[2. 0. 0. ... 0. 2. 2.]


(4032,)

In [111]:
# x=np.array([df[:,i] for i in range(5,155)])
# print(x)
# print(x.shape)

In [112]:
x=np.array(dftemp2)
print(x)

print(x.shape)
# x_new=[list(i) for i in x[t-1:-1,:]]
# print(x_new)


[[ 1.75003587  0.35034195 -1.34197268 ... -0.09586277 -0.65297501
  -0.69389439]
 [-0.25457839  1.0081691   0.81988383 ...  0.07119234  1.46788294
   0.09901143]
 [-0.54681497 -0.78987671 -0.89669304 ... -0.36733697 -0.45586514
  -0.19349053]
 ...
 [ 2.22086255 -0.58228757 -0.27853416 ... -2.02149798 -1.01073053
   0.43726076]
 [-0.48429916  1.67398747 -0.14923649 ... -1.1054281  -1.40291665
  -0.65378801]
 [-0.49861358 -0.61285237  0.87098058 ... -0.99306681  0.88707099
   0.14605586]]
(4035, 150)


In [113]:
# for i in range(len(x_new)):
#   for j in range(i,i+t):
#     x_new[:,i].append(y[j])

In [114]:
x=np.array(x)
x.shape,y_new.shape

((4035, 150), (4032,))

In [115]:
x_3d=[]
for i in range(4035-t):
  tmp=[]
  for j in range(t):
    tmp.append(x[j+i])
  x_3d.append(tmp)
x_3d= np.array(x_3d)
x_3d.shape

(4032, 3, 150)

In [116]:
train_test_ratio=0.8
x_train=x_3d[:int(x_3d.shape[0]*train_test_ratio)]
x_test=x_3d[int(x_3d.shape[0]*train_test_ratio):]
y_train=y_new[:int(x_3d.shape[0]*train_test_ratio)]
y_test=y_new[int(x_3d.shape[0]*train_test_ratio):]
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((3225, 3, 150), (3225,), (807, 3, 150), (807,))

In [117]:
cnt0=0
cnt1=0
cnt2=0
for i in range(3224):
  if(y_train[i]==0):
    cnt0+=1
  elif(y_train[i]==1):
    cnt1+=1
  elif(y_train[i]==2):
    cnt2+=1
print(cnt0)
print(cnt1)
print(cnt2)  

1487
875
862


In [118]:
xtemp=[]
ytemp=[]
for i in range(len(y_train)):
  xtemp.append(x_train[i]);
  ytemp.append(y_train[i])

In [119]:
# xtemp

In [120]:

cntt0=cnt0
cntt1=873
cntt2=862

for i in range(len(y_train)):
  if(y_train[i]==0):
    continue;
  elif(y_train[i]==1 and cntt1<cntt0):
    xtemp.append(x_train[i])
    ytemp.append(1)
    cntt1+=1
  elif(y_train[i]==1 and cntt1>=cntt0):
    continue
  elif(y_train[i]==2 and cntt2<cntt0):
    xtemp.append(x_train[i])
    ytemp.append(2)
    cntt2+=1
  elif(y_train[i]==2 and cntt2>=cntt0):
    continue

x_train=np.array(xtemp)
y_train=np.array(ytemp)

In [121]:
len(x_train)

4464

In [122]:
cnt0=0
cnt1=0
cnt2=0
for i in range(len(y_train)):
  if(y_train[i]==0):
    cnt0+=1
  elif(y_train[i]==1):
    cnt1+=1
  elif(y_train[i]==2):
    cnt2+=1
print(cnt0)
print(cnt1)
print(cnt2)  

1487
1490
1487


In [123]:
len(y_train)

4464

In [124]:
y_train

array([0., 0., 2., ..., 2., 2., 2.])

In [125]:
sklearn_weights=class_weight.compute_class_weight(class_weight='balanced',classes=np.unique(y_train),y=y_train)
sklearn_weights=dict(zip(np.unique(y_train),sklearn_weights))
sklearn_weights

{0.0: 1.0006724949562877, 1.0: 0.9986577181208054, 2.0: 1.0006724949562877}

In [126]:
# cnt0=0
# cnt1=0
# cnt2=0
# for i in range(3*862):
#   if(y_train[i]==0):
#     cnt0+=1
#   elif(y_train[i]==1):
#     cnt1+=1
#   elif(y_train[i]==2):
#     cnt2+=1
# print(cnt0)
# print(cnt1)
# print(cnt2)  

In [127]:

# model = Sequential()
# model.add(LSTM(200, activation='relu', return_sequences=True, input_shape=( t,150,)))
# model.add(LSTM(100, activation='relu', return_sequences=True))
# model.add(LSTM(50, activation='relu', return_sequences=True))
# model.add(LSTM(25, activation='relu'))
# model.add(Dense(20, activation='relu'))
# model.add(Dense(10, activation='relu'))
# model.add(Dense(3))
# model.compile(optimizer='SGD', loss='sparse_categorical_crossentropy',metrics=['accuracy'])
# history = model.fit(x_train, y_train, epochs=10, validation_split=0.2, verbose=1)
# test_output = model.predict(x_test, verbose=1)
# # history = model.fit(X, Y, epochs=1000, validation_split=0.2, verbose=1)
# # test_output = model.predict(x=, verbose=0)
# # print(test_output)

In [ ]:
import keras 
sklearn_weights={0:1738,1:2348,2:2362}
model = Sequential()
model.add(LSTM(200, activation='relu', return_sequences=True, input_shape=( t,150,)))
model.add(LSTM(400, activation='relu', return_sequences=True))
model.add(LSTM(800, activation='relu', return_sequences=True))
model.add(LSTM(150, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(3,activation='sigmoid'))
optimi=keras.optimizers.Adam(lr=0.003)
model.compile(optimizer=optimi, loss='sparse_categorical_crossentropy',metrics=['accuracy'])




history = model.fit(x_train, y_train, epochs=30, validation_split=0.2, verbose=1)


# history = model.fit(x_train, y_train, epochs=5, validation_split=0.2, verbose=1,class_weight=sklearn_weights)
test_output = model.predict(x_test, verbose=1)
# history = model.fit(X, Y, epochs=1000, validation_split=0.2, verbose=1)
# test_output = model.predict(x=, verbose=0)
# print(test_output)

Epoch 1/30


/usr/local/lib/python3.7/dist-packages/keras/optimizers/optimizer_v2/adam.py:110: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


112/112 [==============================] - 8s 37ms/step - loss: 1.0823 - accuracy: 0.4184 - val_loss: 1.2100 - val_accuracy: 0.0235
Epoch 2/30
112/112 [==============================] - 4s 32ms/step - loss: 1.0467 - accuracy: 0.4329 - val_loss: 1.0528 - val_accuracy: 0.3953
Epoch 3/30
112/112 [==============================] - 4s 31ms/step - loss: 0.9143 - accuracy: 0.5942 - val_loss: 0.8565 - val_accuracy: 0.6137
Epoch 4/30
  9/112 [=>............................] - ETA: 3s - loss: 0.6916 - accuracy: 0.7118

In [ ]:
test_output.size

In [ ]:


test_output_1=np.array([np.argmax(i)  for i in test_output])
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,test_output_1))
test_output=pd.DataFrame(test_output)
print(accuracy_score(y_test,test_output_1))


In [ ]:
y_train.shape

In [ ]:
# # print(confusion_matrix(y_test,test_output))
# y_test
test_output_1